apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: unemployed-crimson-swan
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unemployed-crimson-swan 
  name: unemployed-crimson-swan
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: unemployed-crimson-swan 
